-- SEDA TV/REF/LDY: Magalu and Casas Bahia approved cross-field checks.
-- Run with DBeaver after deploying the adapter. Includes recommendation_intent;
-- the earlier recommendation-only setup is not required separately.
-- Scope: inspection D -> source D-1, latest MAIN batch and its MAIN/BSR rows.
-- Summary disappearance: most recent prior record within 5 calendar days;
-- both bodies present before, detailed body still present, summary now missing.
-- Savings/discount rules are intentionally excluded. Other countries unchanged.
-- Repeatable: update existing IDs so manual confirmations remain attached.
BEGIN;
CREATE TEMP TABLE _seda_crossfield_seed (
    product_line text, section_code text, section_name text, table_name text,
    detail_code text, detail_name text, retailer text, validation_type text,
    field1 text, field2 text, error_message text, select_fields text, sort_order integer
) ON COMMIT DROP;
INSERT INTO _seda_crossfield_seed VALUES
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_rank_page_type', '페이지 유형과 순위 필드 일치', 'Magalu', 'rank_page_type', 'page_type', 'main_rank', 'MAIN이면 main_rank, BSR이면 bsr_rank가 있어야 합니다. 두 순위가 함께 있는 것은 허용합니다.', 'page_type|main_rank|bsr_rank', 10),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_rank_page_type', '페이지 유형과 순위 필드 일치', 'Casas Bahia', 'rank_page_type', 'page_type', 'main_rank', 'MAIN이면 main_rank, BSR이면 bsr_rank가 있어야 합니다. 두 순위가 함께 있는 것은 허용합니다.', 'page_type|main_rank|bsr_rank', 10),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_final_original_price', '원가보다 높은 최종가', 'Magalu', 'final_original_price', 'original_sku_price', 'final_sku_price', '두 가격이 유효한 브라질 헤알 금액일 때 원가 < 최종가이면 이상입니다. 같은 가격은 정상입니다.', 'original_sku_price|final_sku_price|savings', 20),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_final_original_price', '원가보다 높은 최종가', 'Casas Bahia', 'final_original_price', 'original_sku_price', 'final_sku_price', '두 가격이 유효한 브라질 헤알 금액일 때 원가 < 최종가이면 이상입니다. 같은 가격은 정상입니다.', 'original_sku_price|final_sku_price|savings', 20),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_zero_body', '리뷰 수 0인데 본문 있음', 'Magalu', 'review_zero_body', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 0인데 상세본문이 있으면 이상입니다. review 번호를 해석할 수 없어도 적용합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 30),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_zero_body', '리뷰 수 0인데 본문 있음', 'Casas Bahia', 'review_zero_body', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 0인데 상세본문이 있으면 이상입니다. review 번호를 해석할 수 없어도 적용합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 30),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_body_over_count', '리뷰 수보다 많은 리뷰본문', 'Magalu', 'review_body_over_count', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 양수이고 수집된 review 번호의 개수가 리뷰 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 40),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_body_over_count', '리뷰 수보다 많은 리뷰본문', 'Casas Bahia', 'review_body_over_count', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 양수이고 수집된 review 번호의 개수가 리뷰 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 40),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_body_count', '리뷰본문 불일치 확인', 'Magalu', 'review_body_count', 'count_of_reviews', 'detailed_review_content', 'Lowes 방식으로 리뷰 수가 양수인데 본문이 없거나, 리뷰 수가 20 이상인데 review20까지 수집되지 않았으면 확인 필요입니다. 본문 번호를 해석할 수 없는 경우도 확인 필요입니다. 리뷰 수 0의 본문 존재와 본문 수 초과는 별도 이상치로 처리합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 50),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_body_count', '리뷰본문 불일치 확인', 'Casas Bahia', 'review_body_count', 'count_of_reviews', 'detailed_review_content', 'Lowes 방식으로 리뷰 수가 양수인데 본문이 없거나, 리뷰 수가 20 이상인데 review20까지 수집되지 않았으면 확인 필요입니다. 본문 번호를 해석할 수 없는 경우도 확인 필요입니다. 리뷰 수 0의 본문 존재와 본문 수 초과는 별도 이상치로 처리합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 50),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_rating_count_presence', '별점과 카운트의 0값 일치', 'Magalu', 'rating_count_presence', 'star_rating', 'count_of_star_ratings', '별점과 별점 수 중 한쪽만 0이면 이상입니다. Casas Bahia는 별점과 리뷰 수도 비교합니다. Magalu의 별점·별점 수가 양수이고 리뷰 수가 0인 경우는 허용합니다. 빈값은 0으로 바꾸지 않습니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 60),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_rating_count_presence', '별점과 카운트의 0값 일치', 'Casas Bahia', 'rating_count_presence', 'star_rating', 'count_of_star_ratings', '별점과 별점 수 중 한쪽만 0이면 이상입니다. Casas Bahia는 별점과 리뷰 수도 비교합니다. Magalu의 별점·별점 수가 양수이고 리뷰 수가 0인 경우는 허용합니다. 빈값은 0으로 바꾸지 않습니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 60),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_reviews_require_rating', '리뷰 수가 있는데 별점 정보 없음', 'Magalu', 'reviews_require_rating', 'count_of_reviews', 'star_rating', '리뷰 수가 양수인데 별점 또는 별점 수가 빈값이나 0이면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 70),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_reviews_require_rating', '리뷰 수가 있는데 별점 정보 없음', 'Casas Bahia', 'reviews_require_rating', 'count_of_reviews', 'star_rating', '리뷰 수가 양수인데 별점 또는 별점 수가 빈값이나 0이면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 70),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_count_match', '리뷰 수와 별점 수 일치', 'Casas Bahia', 'review_count_match', 'count_of_reviews', 'count_of_star_ratings', 'Casas Bahia의 숫자로 수집된 리뷰 수와 별점 수가 다르면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 80),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_review_gt_star_count', '리뷰 수가 별점 수보다 많음', 'Magalu', 'review_gt_star_count', 'count_of_reviews', 'count_of_star_ratings', 'Magalu는 리뷰 수와 별점 수가 다를 수 있지만 리뷰 수가 별점 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 90),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_summary_review_disappeared', '상세리뷰는 있으나 요약리뷰 사라짐', 'Magalu', 'summary_review_disappeared', 'detailed_review_content', 'summarized_review_content', '이전 5일 내 같은 리테일러·상품의 가장 최근 기록에 상세리뷰와 요약리뷰가 모두 있었으나, 현재는 상세리뷰만 있고 요약리뷰가 없으면 확인 필요입니다. 비교 기록이 없으면 판정하지 않습니다.', 'detailed_review_content|summarized_review_content', 100),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_summary_review_disappeared', '상세리뷰는 있으나 요약리뷰 사라짐', 'Casas Bahia', 'summary_review_disappeared', 'detailed_review_content', 'summarized_review_content', '이전 5일 내 같은 리테일러·상품의 가장 최근 기록에 상세리뷰와 요약리뷰가 모두 있었으나, 현재는 상세리뷰만 있고 요약리뷰가 없으면 확인 필요입니다. 비교 기록이 없으면 판정하지 않습니다.', 'detailed_review_content|summarized_review_content', 100),
    ('seda_tv', 'seda_tv_retail', 'SEDA TV', 'dx_seda.dx_seda_tv_retail_com', 'seda_tv_recommendation_intent', '추천 의향 형식·범위', 'Casas Bahia', 'recommendation_intent', 'recommendation_intent', 'count_of_reviews', '추천율 값이 있을 때 NN% recommend this product 형식과 정수 0~100% 범위를 검사합니다. 빈값은 제외하며 리뷰 수와 추천율의 존재 여부를 연결하지 않습니다.', 'recommendation_intent|star_rating|count_of_star_ratings|count_of_reviews', 110),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_rank_page_type', '페이지 유형과 순위 필드 일치', 'Magalu', 'rank_page_type', 'page_type', 'main_rank', 'MAIN이면 main_rank, BSR이면 bsr_rank가 있어야 합니다. 두 순위가 함께 있는 것은 허용합니다.', 'page_type|main_rank|bsr_rank', 10),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_rank_page_type', '페이지 유형과 순위 필드 일치', 'Casas Bahia', 'rank_page_type', 'page_type', 'main_rank', 'MAIN이면 main_rank, BSR이면 bsr_rank가 있어야 합니다. 두 순위가 함께 있는 것은 허용합니다.', 'page_type|main_rank|bsr_rank', 10),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_final_original_price', '원가보다 높은 최종가', 'Magalu', 'final_original_price', 'original_sku_price', 'final_sku_price', '두 가격이 유효한 브라질 헤알 금액일 때 원가 < 최종가이면 이상입니다. 같은 가격은 정상입니다.', 'original_sku_price|final_sku_price|savings', 20),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_final_original_price', '원가보다 높은 최종가', 'Casas Bahia', 'final_original_price', 'original_sku_price', 'final_sku_price', '두 가격이 유효한 브라질 헤알 금액일 때 원가 < 최종가이면 이상입니다. 같은 가격은 정상입니다.', 'original_sku_price|final_sku_price|savings', 20),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_zero_body', '리뷰 수 0인데 본문 있음', 'Magalu', 'review_zero_body', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 0인데 상세본문이 있으면 이상입니다. review 번호를 해석할 수 없어도 적용합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 30),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_zero_body', '리뷰 수 0인데 본문 있음', 'Casas Bahia', 'review_zero_body', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 0인데 상세본문이 있으면 이상입니다. review 번호를 해석할 수 없어도 적용합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 30),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_body_over_count', '리뷰 수보다 많은 리뷰본문', 'Magalu', 'review_body_over_count', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 양수이고 수집된 review 번호의 개수가 리뷰 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 40),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_body_over_count', '리뷰 수보다 많은 리뷰본문', 'Casas Bahia', 'review_body_over_count', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 양수이고 수집된 review 번호의 개수가 리뷰 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 40),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_body_count', '리뷰본문 불일치 확인', 'Magalu', 'review_body_count', 'count_of_reviews', 'detailed_review_content', 'Lowes 방식으로 리뷰 수가 양수인데 본문이 없거나, 리뷰 수가 20 이상인데 review20까지 수집되지 않았으면 확인 필요입니다. 본문 번호를 해석할 수 없는 경우도 확인 필요입니다. 리뷰 수 0의 본문 존재와 본문 수 초과는 별도 이상치로 처리합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 50),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_body_count', '리뷰본문 불일치 확인', 'Casas Bahia', 'review_body_count', 'count_of_reviews', 'detailed_review_content', 'Lowes 방식으로 리뷰 수가 양수인데 본문이 없거나, 리뷰 수가 20 이상인데 review20까지 수집되지 않았으면 확인 필요입니다. 본문 번호를 해석할 수 없는 경우도 확인 필요입니다. 리뷰 수 0의 본문 존재와 본문 수 초과는 별도 이상치로 처리합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 50),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_rating_count_presence', '별점과 카운트의 0값 일치', 'Magalu', 'rating_count_presence', 'star_rating', 'count_of_star_ratings', '별점과 별점 수 중 한쪽만 0이면 이상입니다. Casas Bahia는 별점과 리뷰 수도 비교합니다. Magalu의 별점·별점 수가 양수이고 리뷰 수가 0인 경우는 허용합니다. 빈값은 0으로 바꾸지 않습니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 60),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_rating_count_presence', '별점과 카운트의 0값 일치', 'Casas Bahia', 'rating_count_presence', 'star_rating', 'count_of_star_ratings', '별점과 별점 수 중 한쪽만 0이면 이상입니다. Casas Bahia는 별점과 리뷰 수도 비교합니다. Magalu의 별점·별점 수가 양수이고 리뷰 수가 0인 경우는 허용합니다. 빈값은 0으로 바꾸지 않습니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 60),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_reviews_require_rating', '리뷰 수가 있는데 별점 정보 없음', 'Magalu', 'reviews_require_rating', 'count_of_reviews', 'star_rating', '리뷰 수가 양수인데 별점 또는 별점 수가 빈값이나 0이면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 70),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_reviews_require_rating', '리뷰 수가 있는데 별점 정보 없음', 'Casas Bahia', 'reviews_require_rating', 'count_of_reviews', 'star_rating', '리뷰 수가 양수인데 별점 또는 별점 수가 빈값이나 0이면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 70),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_count_match', '리뷰 수와 별점 수 일치', 'Casas Bahia', 'review_count_match', 'count_of_reviews', 'count_of_star_ratings', 'Casas Bahia의 숫자로 수집된 리뷰 수와 별점 수가 다르면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 80),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_review_gt_star_count', '리뷰 수가 별점 수보다 많음', 'Magalu', 'review_gt_star_count', 'count_of_reviews', 'count_of_star_ratings', 'Magalu는 리뷰 수와 별점 수가 다를 수 있지만 리뷰 수가 별점 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 90),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_summary_review_disappeared', '상세리뷰는 있으나 요약리뷰 사라짐', 'Magalu', 'summary_review_disappeared', 'detailed_review_content', 'summarized_review_content', '이전 5일 내 같은 리테일러·상품의 가장 최근 기록에 상세리뷰와 요약리뷰가 모두 있었으나, 현재는 상세리뷰만 있고 요약리뷰가 없으면 확인 필요입니다. 비교 기록이 없으면 판정하지 않습니다.', 'detailed_review_content|summarized_review_content', 100),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_summary_review_disappeared', '상세리뷰는 있으나 요약리뷰 사라짐', 'Casas Bahia', 'summary_review_disappeared', 'detailed_review_content', 'summarized_review_content', '이전 5일 내 같은 리테일러·상품의 가장 최근 기록에 상세리뷰와 요약리뷰가 모두 있었으나, 현재는 상세리뷰만 있고 요약리뷰가 없으면 확인 필요입니다. 비교 기록이 없으면 판정하지 않습니다.', 'detailed_review_content|summarized_review_content', 100),
    ('seda_ref', 'seda_ref_retail', 'SEDA REF', 'dx_seda.dx_seda_ref_retail_com', 'seda_ref_recommendation_intent', '추천 의향 형식·범위', 'Casas Bahia', 'recommendation_intent', 'recommendation_intent', 'count_of_reviews', '추천율 값이 있을 때 NN% recommend this product 형식과 정수 0~100% 범위를 검사합니다. 빈값은 제외하며 리뷰 수와 추천율의 존재 여부를 연결하지 않습니다.', 'recommendation_intent|star_rating|count_of_star_ratings|count_of_reviews', 110),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_rank_page_type', '페이지 유형과 순위 필드 일치', 'Magalu', 'rank_page_type', 'page_type', 'main_rank', 'MAIN이면 main_rank, BSR이면 bsr_rank가 있어야 합니다. 두 순위가 함께 있는 것은 허용합니다.', 'page_type|main_rank|bsr_rank', 10),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_rank_page_type', '페이지 유형과 순위 필드 일치', 'Casas Bahia', 'rank_page_type', 'page_type', 'main_rank', 'MAIN이면 main_rank, BSR이면 bsr_rank가 있어야 합니다. 두 순위가 함께 있는 것은 허용합니다.', 'page_type|main_rank|bsr_rank', 10),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_final_original_price', '원가보다 높은 최종가', 'Magalu', 'final_original_price', 'original_sku_price', 'final_sku_price', '두 가격이 유효한 브라질 헤알 금액일 때 원가 < 최종가이면 이상입니다. 같은 가격은 정상입니다.', 'original_sku_price|final_sku_price|savings', 20),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_final_original_price', '원가보다 높은 최종가', 'Casas Bahia', 'final_original_price', 'original_sku_price', 'final_sku_price', '두 가격이 유효한 브라질 헤알 금액일 때 원가 < 최종가이면 이상입니다. 같은 가격은 정상입니다.', 'original_sku_price|final_sku_price|savings', 20),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_zero_body', '리뷰 수 0인데 본문 있음', 'Magalu', 'review_zero_body', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 0인데 상세본문이 있으면 이상입니다. review 번호를 해석할 수 없어도 적용합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 30),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_zero_body', '리뷰 수 0인데 본문 있음', 'Casas Bahia', 'review_zero_body', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 0인데 상세본문이 있으면 이상입니다. review 번호를 해석할 수 없어도 적용합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 30),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_body_over_count', '리뷰 수보다 많은 리뷰본문', 'Magalu', 'review_body_over_count', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 양수이고 수집된 review 번호의 개수가 리뷰 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 40),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_body_over_count', '리뷰 수보다 많은 리뷰본문', 'Casas Bahia', 'review_body_over_count', 'count_of_reviews', 'detailed_review_content', '리뷰 수가 양수이고 수집된 review 번호의 개수가 리뷰 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 40),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_body_count', '리뷰본문 불일치 확인', 'Magalu', 'review_body_count', 'count_of_reviews', 'detailed_review_content', 'Lowes 방식으로 리뷰 수가 양수인데 본문이 없거나, 리뷰 수가 20 이상인데 review20까지 수집되지 않았으면 확인 필요입니다. 본문 번호를 해석할 수 없는 경우도 확인 필요입니다. 리뷰 수 0의 본문 존재와 본문 수 초과는 별도 이상치로 처리합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 50),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_body_count', '리뷰본문 불일치 확인', 'Casas Bahia', 'review_body_count', 'count_of_reviews', 'detailed_review_content', 'Lowes 방식으로 리뷰 수가 양수인데 본문이 없거나, 리뷰 수가 20 이상인데 review20까지 수집되지 않았으면 확인 필요입니다. 본문 번호를 해석할 수 없는 경우도 확인 필요입니다. 리뷰 수 0의 본문 존재와 본문 수 초과는 별도 이상치로 처리합니다.', 'star_rating|count_of_star_ratings|count_of_reviews|detailed_review_content', 50),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_rating_count_presence', '별점과 카운트의 0값 일치', 'Magalu', 'rating_count_presence', 'star_rating', 'count_of_star_ratings', '별점과 별점 수 중 한쪽만 0이면 이상입니다. Casas Bahia는 별점과 리뷰 수도 비교합니다. Magalu의 별점·별점 수가 양수이고 리뷰 수가 0인 경우는 허용합니다. 빈값은 0으로 바꾸지 않습니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 60),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_rating_count_presence', '별점과 카운트의 0값 일치', 'Casas Bahia', 'rating_count_presence', 'star_rating', 'count_of_star_ratings', '별점과 별점 수 중 한쪽만 0이면 이상입니다. Casas Bahia는 별점과 리뷰 수도 비교합니다. Magalu의 별점·별점 수가 양수이고 리뷰 수가 0인 경우는 허용합니다. 빈값은 0으로 바꾸지 않습니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 60),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_reviews_require_rating', '리뷰 수가 있는데 별점 정보 없음', 'Magalu', 'reviews_require_rating', 'count_of_reviews', 'star_rating', '리뷰 수가 양수인데 별점 또는 별점 수가 빈값이나 0이면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 70),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_reviews_require_rating', '리뷰 수가 있는데 별점 정보 없음', 'Casas Bahia', 'reviews_require_rating', 'count_of_reviews', 'star_rating', '리뷰 수가 양수인데 별점 또는 별점 수가 빈값이나 0이면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 70),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_count_match', '리뷰 수와 별점 수 일치', 'Casas Bahia', 'review_count_match', 'count_of_reviews', 'count_of_star_ratings', 'Casas Bahia의 숫자로 수집된 리뷰 수와 별점 수가 다르면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 80),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_review_gt_star_count', '리뷰 수가 별점 수보다 많음', 'Magalu', 'review_gt_star_count', 'count_of_reviews', 'count_of_star_ratings', 'Magalu는 리뷰 수와 별점 수가 다를 수 있지만 리뷰 수가 별점 수보다 많으면 이상입니다.', 'star_rating|count_of_star_ratings|count_of_reviews', 90),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_summary_review_disappeared', '상세리뷰는 있으나 요약리뷰 사라짐', 'Magalu', 'summary_review_disappeared', 'detailed_review_content', 'summarized_review_content', '이전 5일 내 같은 리테일러·상품의 가장 최근 기록에 상세리뷰와 요약리뷰가 모두 있었으나, 현재는 상세리뷰만 있고 요약리뷰가 없으면 확인 필요입니다. 비교 기록이 없으면 판정하지 않습니다.', 'detailed_review_content|summarized_review_content', 100),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_summary_review_disappeared', '상세리뷰는 있으나 요약리뷰 사라짐', 'Casas Bahia', 'summary_review_disappeared', 'detailed_review_content', 'summarized_review_content', '이전 5일 내 같은 리테일러·상품의 가장 최근 기록에 상세리뷰와 요약리뷰가 모두 있었으나, 현재는 상세리뷰만 있고 요약리뷰가 없으면 확인 필요입니다. 비교 기록이 없으면 판정하지 않습니다.', 'detailed_review_content|summarized_review_content', 100),
    ('seda_ldy', 'seda_ldy_retail', 'SEDA LDY', 'dx_seda.dx_seda_ldy_retail_com', 'seda_ldy_recommendation_intent', '추천 의향 형식·범위', 'Casas Bahia', 'recommendation_intent', 'recommendation_intent', 'count_of_reviews', '추천율 값이 있을 때 NN% recommend this product 형식과 정수 0~100% 범위를 검사합니다. 빈값은 제외하며 리뷰 수와 추천율의 존재 여부를 연결하지 않습니다.', 'recommendation_intent|star_rating|count_of_star_ratings|count_of_reviews', 110);

UPDATE public.monitoring_validation_rules AS target
SET section_name = seed.section_name, detail_name = seed.detail_name,
    date_column = 'crawl_strdatetime', product_line = seed.product_line,
    retailer = seed.retailer, field1 = seed.field1, field2 = seed.field2,
    validation_type = seed.validation_type, check_type = 'cross_field',
    error_message = seed.error_message, display_columns = seed.select_fields,
    select_fields = seed.select_fields, query = '', query_detail = '',
    sort_order = seed.sort_order, is_active = TRUE
FROM _seda_crossfield_seed AS seed
WHERE target.rule_type = 'crossfield'
  AND target.section_code = seed.section_code AND target.table_name = seed.table_name
  AND target.detail_code = seed.detail_code
  AND LOWER(REPLACE(BTRIM(target.retailer), ' ', '')) = LOWER(REPLACE(seed.retailer, ' ', ''));

INSERT INTO public.monitoring_validation_rules (
    rule_type, section_code, section_name, detail_code, detail_name,
    table_name, date_column, product_line, retailer, field1, field2,
    validation_type, check_type, error_message, display_columns, select_fields,
    query, query_detail, sort_order, is_active, created_at, created_id
)
SELECT 'crossfield', seed.section_code, seed.section_name, seed.detail_code,
       seed.detail_name, seed.table_name, 'crawl_strdatetime', seed.product_line,
       seed.retailer, seed.field1, seed.field2, seed.validation_type, 'cross_field',
       seed.error_message, seed.select_fields, seed.select_fields,
       '', '', seed.sort_order, TRUE, NOW(), 'setup_seda_crossfield'
FROM _seda_crossfield_seed AS seed
WHERE NOT EXISTS (
    SELECT 1 FROM public.monitoring_validation_rules AS target
    WHERE target.rule_type = 'crossfield'
      AND target.section_code = seed.section_code AND target.table_name = seed.table_name
      AND target.detail_code = seed.detail_code
      AND LOWER(REPLACE(BTRIM(target.retailer), ' ', '')) = LOWER(REPLACE(seed.retailer, ' ', ''))
);

-- Expected: 57 retailer-specific rows, combined into 11 rule cards per product.
SELECT target.section_code, target.retailer, COUNT(*) AS active_rules
FROM public.monitoring_validation_rules target
JOIN _seda_crossfield_seed seed
  ON target.section_code = seed.section_code AND target.table_name = seed.table_name
 AND target.detail_code = seed.detail_code
 AND LOWER(REPLACE(BTRIM(target.retailer), ' ', '')) = LOWER(REPLACE(seed.retailer, ' ', ''))
WHERE target.rule_type = 'crossfield' AND target.is_active
GROUP BY target.section_code, target.retailer
ORDER BY target.section_code, target.retailer;
COMMIT;
